In [1]:
!gdown 136oQPFJqG0vugwm0oAOU9IxwJN0zT54K

Downloading...
From: https://drive.google.com/uc?id=136oQPFJqG0vugwm0oAOU9IxwJN0zT54K
To: /content/Pokemon.csv
100% 44.0k/44.0k [00:00<00:00, 124MB/s]

In [6]:
import pandas as pd
import numpy as np

In [73]:
data = pd.read_csv('/content/Pokemon.csv')

## Create an example DataFrame

In [74]:
df = pd.DataFrame({'col one':[100, 200], 'col two':[300, 400]})
df

   col one  col two
0      100      300
1      200      400

In [75]:
pd.DataFrame(np.random.rand(4, 8), columns=list('abcdefgh'))

,a,b,c,d,e,f,g,h
0,0.211025,0.148126,0.679437,0.287645,0.035275,0.285124,0.313314,0.121054
1,0.361451,0.996439,0.401521,0.234080,0.103908,0.838070,0.256617,0.584056
2,0.243553,0.059943,0.055316,0.450530,0.190026,0.782297,0.856126,0.569080
3,0.600643,0.975051,0.519675,0.140729,0.668187,0.905942,0.035337,0.088676

In [76]:
pd.util.testing.makeDataFrame().head()

                   A         B         C         D
xIH13iGHP4  0.919202 -1.084965 -0.330164 -1.681841
aoHAyo00Pl  1.544368  0.193910 -0.398716 -0.267523
zmuQV32no7  0.345481  1.011625  0.335001  1.620216
GC0TzYhnKm  0.841254 -1.780052 -0.098154  0.430689
D4PEbuD1mA  0.623624 -0.089280 -2.289458  0.765787

In [77]:
pd.util.testing.makeMissingDataframe().head()

                   A         B         C         D
Aofppt6N5E  0.623790 -0.328395 -0.818650       NaN
8yuDdHh8iR -0.080803  1.701066 -0.429203  0.206966
upf4USKDGK -0.409490 -1.072827 -0.927823 -0.768411
2Yv5nnV7aw  0.938424  0.249246  1.671093       NaN
DQK1ZuR6mg  1.261938       NaN       NaN  1.304154

In [78]:
pd.util.testing.makeTimeDataFrame().head()

                   A         B         C         D
2000-01-03 -0.133812  1.550887 -0.026166  0.686443
2000-01-04  1.036991  1.307356 -1.483159 -1.304558
2000-01-05  0.766995 -0.075220  0.408392 -0.267696
2000-01-06 -1.199219 -1.640139  0.487682 -0.253413
2000-01-07  0.681742 -0.897427 -0.089646  0.004583

In [79]:
pd.util.testing.makeMixedDataFrame()

     A    B     C          D
0  0.0  0.0  foo1 2009-01-01
1  1.0  1.0  foo2 2009-01-02
2  2.0  0.0  foo3 2009-01-05
3  3.0  1.0  foo4 2009-01-06
4  4.0  0.0  foo5 2009-01-07

In [80]:
# And many more
[x for x in dir(pd.util.testing) if x.startswith('make')]

['makeBoolIndex',
 'makeCategoricalIndex',
 'makeCustomDataframe',
 'makeCustomIndex',
 'makeDataFrame',
 'makeDateIndex',
 'makeFloatIndex',
 'makeFloatSeries',
 'makeIntIndex',
 'makeIntervalIndex',
 'makeMissingDataframe',
 'makeMixedDataFrame',
 'makeMultiIndex',
 'makeNumericIndex',
 'makeObjectSeries',
 'makePeriodFrame',
 'makePeriodIndex',
 'makePeriodSeries',
 'makeRangeIndex',
 'makeStringIndex',
 'makeStringSeries',
 'makeTimeDataFrame',
 'makeTimeSeries',
 'makeTimedeltaIndex',
 'makeUIntIndex',
 'make_rand_series']

## Reverse Row/Column order

### Row

In [81]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [82]:
data.loc[::-1].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

In [83]:
data.loc[::-1].reset_index(drop=True).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
1,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
2,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
3,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
4,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

### Column

In [84]:
data.loc[:, ::-1].head()

,Legendary,Generation,Speed,Sp. Def,Sp. Atk,Defense,Attack,HP,Total,Type 2,Type 1,Name,#
0,False,1,45,65,65,49,49,45,318,Poison,Grass,Bulbasaur,1
1,False,1,60,80,80,63,62,60,405,Poison,Grass,Ivysaur,2
2,False,1,80,100,100,83,82,80,525,Poison,Grass,Venusaur,3
3,False,1,80,120,122,123,100,80,625,Poison,Grass,VenusaurMega Venusaur,3
4,False,1,65,50,60,43,52,39,309,NaN,Fire,Charmander,4

## Select column by data type

In [85]:
data.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [86]:
data.select_dtypes(include='number').head()

   #  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0  1    318  45      49       49       65       65     45           1
1  2    405  60      62       63       80       80     60           1
2  3    525  80      82       83      100      100     80           1
3  3    625  80     100      123      122      120     80           1
4  4    309  39      52       43       60       50     65           1

In [87]:
data.select_dtypes(include='object').head()

                    Name Type 1  Type 2
0              Bulbasaur  Grass  Poison
1                Ivysaur  Grass  Poison
2               Venusaur  Grass  Poison
3  VenusaurMega Venusaur  Grass  Poison
4             Charmander   Fire     NaN

In [88]:
data.select_dtypes(include=['number', 'object']).head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1

In [89]:
data.select_dtypes(exclude=['number', 'object']).head()

   Legendary
0      False
1      False
2      False
3      False
4      False

## Convert strings to numbers

In [90]:
df = pd.DataFrame({'col_one':['1.1', '2.2', '3.3'],
                   'col_two':['4.4', '5.5', '6.6'],
                   'col_three':['7.7', '8.8', '-']})
df

  col_one col_two col_three
0     1.1     4.4       7.7
1     2.2     5.5       8.8
2     3.3     6.6         -

In [91]:
df.dtypes

col_one      object
col_two      object
col_three    object
dtype: object

In [92]:
df.astype({'col_one':'float', 'col_two':'float'}).dtypes

col_one      float64
col_two      float64
col_three     object
dtype: object

In [93]:
df.astype({'col_one':'float', 'col_two':'float', 'col_three': 'float'}).dtypes

ValueError: ignored

In [94]:
pd.to_numeric(df.col_three, errors='coerce')

0    7.7
1    8.8
2    NaN
Name: col_three, dtype: float64

In [95]:
pd.to_numeric(df.col_three, errors='coerce').fillna(0)

0    7.7
1    8.8
2    0.0
Name: col_three, dtype: float64

In [96]:
df = df.apply(pd.to_numeric, errors='coerce').fillna(0)
df

   col_one  col_two  col_three
0      1.1      4.4        7.7
1      2.2      5.5        8.8
2      3.3      6.6        0.0

In [97]:
df.dtypes

col_one      float64
col_two      float64
col_three    float64
dtype: object

## Dealing with large Dataset

### Check memery usage

In [98]:
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 194.7 KB

### Load in specific Columns

In [99]:
cols = ['Name', 'Type 1']
small_data = pd.read_csv('/content/Pokemon.csv', usecols=cols)
small_data.head()

                    Name Type 1
0              Bulbasaur  Grass
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass
4             Charmander   Fire

In [100]:
small_data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    800 non-null    object
 1   Type 1  800 non-null    object
dtypes: object(2)
memory usage: 100.3 KB

In [101]:
dtypes = {'Type 1':'category'}
smaller_data = pd.read_csv('/content/Pokemon.csv', usecols=cols, dtype=dtypes)
smaller_data.head()

                    Name Type 1
0              Bulbasaur  Grass
1                Ivysaur  Grass
2               Venusaur  Grass
3  VenusaurMega Venusaur  Grass
4             Charmander   Fire

In [102]:
smaller_data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    800 non-null    object
 1   Type 1  800 non-null    category
dtypes: category(1), object(1)
memory usage: 54.1 KB

### Load in Chunks

In [103]:
chunks_df = pd.read_csv('/content/Pokemon.csv', chunksize=100)

In [104]:
next(chunks_df)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False

In [105]:
for i, df in enumerate(pd.read_csv('/content/Pokemon.csv', chunksize=100)):
    df.to_csv(f'/content/Pokemon_{i}.csv', index=False)

In [106]:
df0 = pd.read_csv('/content/Pokemon_0.csv')
df0.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [107]:
df1 = pd.read_csv('/content/Pokemon_1.csv')
df1.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
1,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
2,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
3,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
4,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False

## Build a DataFrame from multiple files (row-wise)

In [108]:
df0.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [109]:
df1.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
1,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
2,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
3,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
4,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False

In [110]:
df = pd.concat([df0, df1])
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
96,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
97,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
98,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
99,184,Azumarill,Water,Fairy,420,100,50,80,60,80,50,2,False

In [111]:
df[95:105]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
0,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
1,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
2,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
3,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
4,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False

In [112]:
df = pd.concat([df0, df1], ignore_index=True)
df[95:105]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False

## Build a DataFrame from multiple files (column-wise)

In [113]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [114]:
print(data.columns[:6])
print(data.columns[6:])

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP'], dtype='object')
Index(['Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation',
       'Legendary'],
      dtype='object')

In [115]:
data.to_csv('/content/Pokemon_first.csv', columns=data.columns[:6], index=False)
data.to_csv('/content/Pokemon_second.csv', columns=data.columns[6:], index=False)

In [116]:
df_f = pd.read_csv('/content/Pokemon_first.csv')
df_f.head()

   #                   Name Type 1  Type 2  Total  HP
0  1              Bulbasaur  Grass  Poison    318  45
1  2                Ivysaur  Grass  Poison    405  60
2  3               Venusaur  Grass  Poison    525  80
3  3  VenusaurMega Venusaur  Grass  Poison    625  80
4  4             Charmander   Fire     NaN    309  39

In [117]:
df_s = pd.read_csv('/content/Pokemon_second.csv')
df_s.head()

   Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0      49       49       65       65     45           1      False
1      62       63       80       80     60           1      False
2      82       83      100      100     80           1      False
3     100      123      122      120     80           1      False
4      52       43       60       50     65           1      False

In [118]:
df = pd.concat([df_f, df_s], axis='columns')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## Split a DataFrame into two random subsets

In [119]:
len(data)

800

In [120]:
data_1 = data.sample(frac=0.75, random_state=1234)

In [121]:
data_2 = data.drop(data_1.index)

In [122]:
len(data_1) + len(data_2)

800

## Handle missing values

In [123]:
data.isna().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [124]:
data.isna().mean()

#             0.0000
Name          0.0000
Type 1        0.0000
Type 2        0.4825
Total         0.0000
HP            0.0000
Attack        0.0000
Defense       0.0000
Sp. Atk       0.0000
Sp. Def       0.0000
Speed         0.0000
Generation    0.0000
Legendary     0.0000
dtype: float64

In [125]:
data.dropna(axis='rows')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [128]:
data.dropna(axis='columns', thresh=len(data)*0.6).head()

,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,309,39,52,43,60,50,65,1,False

In [131]:
data.fillna('None Type')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,None Type,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [129]:
data.interpolate()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Split a string into multiple columns

In [61]:
df = pd.DataFrame({'name':['John Arthur Doe', 'Jane Ann Smith'],
                   'location':['Los Angeles, CA', 'Washington, DC']})
df

              name         location
0  John Arthur Doe  Los Angeles, CA
1   Jane Ann Smith   Washington, DC

In [62]:
df[['first', 'middle', 'last']] = df.name.str.split(' ', expand=True)
df

              name         location first  middle   last
0  John Arthur Doe  Los Angeles, CA  John  Arthur    Doe
1   Jane Ann Smith   Washington, DC  Jane     Ann  Smith

## Reshape a MultiIndexed Series

In [68]:
data.groupby(['Type 1', 'Legendary'])['#'].count()

Type 1    Legendary
Bug       False         69
Dark      False         29
          True           2
Dragon    False         20
          True          12
Electric  False         40
          True           4
Fairy     False         16
          True           1
Fighting  False         27
Fire      False         47
          True           5
Flying    False          2
          True           2
Ghost     False         30
          True           2
Grass     False         67
          True           3
Ground    False         28
          True           4
Ice       False         22
          True           2
Normal    False         96
          True           2
Poison    False         28
Psychic   False         43
          True          14
Rock      False         40
          True           4
Steel     False         23
          True           4
Water     False        108
          True           4
Name: #, dtype: int64

In [133]:
f = data.groupby(['Type 1', 'Legendary'])['#'].count().unstack()
f

Legendary  False  True
Type 1
Bug         69.0    NaN
Dark        29.0    2.0
Dragon      20.0   12.0
Electric    40.0    4.0
Fairy       16.0    1.0
Fighting    27.0    NaN
Fire        47.0    5.0
Flying       2.0    2.0
Ghost       30.0    2.0
Grass       67.0    3.0
Ground      28.0    4.0
Ice         22.0    2.0
Normal      96.0    2.0
Poison      28.0    NaN
Psychic     43.0   14.0
Rock        40.0    4.0
Steel       23.0    4.0
Water      108.0    4.0

## Reshape a DataFrame from wide format to long format

In [137]:
f = data[['Name', 'HP', 'Attack']].iloc[:5]
f

                    Name  HP  Attack
0              Bulbasaur  45      49
1                Ivysaur  60      62
2               Venusaur  80      82
3  VenusaurMega Venusaur  80     100
4             Charmander  39      52

In [138]:
f2 = f.melt(id_vars='Name', var_name='Stats', value_name='Point')
f2

                    Name   Stats  Point
0              Bulbasaur      HP     45
1                Ivysaur      HP     60
2               Venusaur      HP     80
3  VenusaurMega Venusaur      HP     80
4             Charmander      HP     39
5              Bulbasaur  Attack     49
6                Ivysaur  Attack     62
7               Venusaur  Attack     82
8  VenusaurMega Venusaur  Attack    100
9             Charmander  Attack     52

## Create a pivot table

In [70]:
data.pivot_table(index='Type 1', columns='Legendary', values='#', aggfunc='count')

Legendary  False  True
Type 1
Bug         69.0    NaN
Dark        29.0    2.0
Dragon      20.0   12.0
Electric    40.0    4.0
Fairy       16.0    1.0
Fighting    27.0    NaN
Fire        47.0    5.0
Flying       2.0    2.0
Ghost       30.0    2.0
Grass       67.0    3.0
Ground      28.0    4.0
Ice         22.0    2.0
Normal      96.0    2.0
Poison      28.0    NaN
Psychic     43.0   14.0
Rock        40.0    4.0
Steel       23.0    4.0
Water      108.0    4.0

In [72]:
data.pivot_table(index='Type 1', columns='Legendary', values='#', aggfunc='count', margins=True)

Legendary  False  True  All
Type 1
Bug         69.0   NaN   69
Dark        29.0   2.0   31
Dragon      20.0  12.0   32
Electric    40.0   4.0   44
Fairy       16.0   1.0   17
Fighting    27.0   NaN   27
Fire        47.0   5.0   52
Flying       2.0   2.0    4
Ghost       30.0   2.0   32
Grass       67.0   3.0   70
Ground      28.0   4.0   32
Ice         22.0   2.0   24
Normal      96.0   2.0   98
Poison      28.0   NaN   28
Psychic     43.0  14.0   57
Rock        40.0   4.0   44
Steel       23.0   4.0   27
Water      108.0   4.0  112
All        735.0  65.0  800

## Convert continuous data into categorical data

In [139]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [140]:
pd.cut(data['Attack'], bins=[0, 50, 100, 150, np.inf], labels=['weak', 'normal', 'strong', 'nani?!']).head(10)

0      weak
1    normal
2    normal
3    normal
4    normal
5    normal
6    normal
7    strong
8    strong
9      weak
Name: Attack, dtype: category
Categories (4, object): ['weak' < 'normal' < 'strong' < 'nani?!']

In [141]:
df = data
df['Attack'] = pd.cut(data['Attack'], bins=[0, 50, 100, 150, np.inf], labels=['weak', 'normal', 'strong', 'nani?!'])

In [142]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,weak,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,normal,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,normal,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,normal,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,normal,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,normal,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,nani?!,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,strong,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,nani?!,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,strong,120,130,90,70,6,True

## Profile a DataFrame

In [143]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,weak,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,normal,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,normal,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,normal,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,normal,43,60,50,65,1,False

In [146]:
data.describe()

,#,Total,HP,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [149]:
# !pip install pandas-profiling
from pandas_profiling import ProfileReport

In [150]:
ProfileReport(data)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]