In [1]:
import pandas as pd
import numpy as np

df_train = pd.read_csv('weatherHistory_training_nan.csv')
print(df_train.shape)
df_train.head(15)

(70000, 2)

                   Formatted Date  Temperature (C)
0   2006-01-01 00:00:00.000 +0100         0.577778
1   2006-01-01 01:00:00.000 +0100         1.161111
2   2006-01-01 02:00:00.000 +0100         1.666667
3   2006-01-01 03:00:00.000 +0100         1.711111
4   2006-01-01 04:00:00.000 +0100         1.183333
5   2006-01-01 05:00:00.000 +0100         1.205556
6   2006-01-01 06:00:00.000 +0100         2.222222
7   2006-01-01 07:00:00.000 +0100         2.072222
8   2006-01-01 08:00:00.000 +0100         2.200000
9   2006-01-01 09:00:00.000 +0100              NaN
10  2006-01-01 10:00:00.000 +0100         2.788889
11  2006-01-01 11:00:00.000 +0100              NaN
12  2006-01-01 12:00:00.000 +0100         4.911111
13  2006-01-01 13:00:00.000 +0100         6.205556
14  2006-01-01 14:00:00.000 +0100              NaN

In [2]:
mean = df_train['Temperature (C)'].mean()
print(mean)

df_train = df_train.fillna(mean)
df_train.head(15)

11.832714120961404

                   Formatted Date  Temperature (C)
0   2006-01-01 00:00:00.000 +0100         0.577778
1   2006-01-01 01:00:00.000 +0100         1.161111
2   2006-01-01 02:00:00.000 +0100         1.666667
3   2006-01-01 03:00:00.000 +0100         1.711111
4   2006-01-01 04:00:00.000 +0100         1.183333
5   2006-01-01 05:00:00.000 +0100         1.205556
6   2006-01-01 06:00:00.000 +0100         2.222222
7   2006-01-01 07:00:00.000 +0100         2.072222
8   2006-01-01 08:00:00.000 +0100         2.200000
9   2006-01-01 09:00:00.000 +0100        11.832714
10  2006-01-01 10:00:00.000 +0100         2.788889
11  2006-01-01 11:00:00.000 +0100        11.832714
12  2006-01-01 12:00:00.000 +0100         4.911111
13  2006-01-01 13:00:00.000 +0100         6.205556
14  2006-01-01 14:00:00.000 +0100        11.832714